### ISSUE TITLE
Update readme to include formatting for secretsdump

### ISSUE THREAD

**Issue by 7MinSec** [hackern0v1c3/hash_combiner#2]
Hello!

In the readme, maybe consider adding the tip you showed me on properly formatting a secretsdump so hash_combiner can chew on it.  Here's what you sent me:

````
cat secrets_dump.txt |cut -d'\' -f2 | cut -d':' -f1,4 > secrets_dump_reformated.txt 
````

LOVE this project :-)

Thanks!
Brian

**Comment by hackern0v1c3** [comment]
You got it.
